/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import BancoDeDados.Conexao;
import BancoDeDados.DAO;
import Negocio.Logica;
import cecijava.CeciJava;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gildo Lima
 */
public class ConsultaAlunoResumo extends javax.swing.JFrame {

    public int chave =0;
    public static String nome;
    
      
    /**
     * 
     * Creates new form ConsultaAlunoResumo
     */
    public ConsultaAlunoResumo() {
        initComponents();
        
               
        tblConsulta.setVisible(false);
      
        
        Logica logi = new Logica();
        Conexao cone;
        DAO dao = new DAO(); 
        btnExcluir.setEnabled(false);
        btnConsultar.setEnabled(false);
        
       
        // Buscando todos os dados do banco para exibir no jTable
        ArrayList<Logica>dados = new ArrayList<Logica>();
         try {
             dados = dao.BuscarDadosTodos("select * from aluno, endereco where idAlunofk = idAluno");
         } catch (SQLException ex) {
             Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(Level.SEVERE, null, ex);
         }
       DefaultTableModel modelo = new DefaultTableModel();
     
         modelo.setColumnIdentifiers(new String[]{"Nome", "Nascimento", "Bairro", "Cidade", "Turma"});       
         {
             
             
             
         }
         for(int i=0;i<dados.size();i++) {
             
      
         modelo.addRow(
         new Object[]{dados.get(i).getNome(),dados.get(i).getDataNasc(), dados.get(i).getBairro(), dados.get(i).getCidade(),dados.get(i).getTurma()});
        
         
         tblConsulta.setModel(modelo);
         }  
         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();
        txtNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnConsultar1 = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        tblConsulta.setAutoCreateRowSorter(true);
        tblConsulta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Teste(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tblConsultaMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tblConsulta);

        btnVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/voltar1.png"))); // NOI18N
        btnVoltar.setBorderPainted(false);
        btnVoltar.setContentAreaFilled(false);
        btnVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        txtNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Digite o nome do aluno");

        btnConsultar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/filtrar1.png"))); // NOI18N
        btnConsultar1.setBorderPainted(false);
        btnConsultar1.setContentAreaFilled(false);
        btnConsultar1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultar1ActionPerformed(evt);
            }
        });

        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/consultar2.png"))); // NOI18N
        btnConsultar.setBorderPainted(false);
        btnConsultar.setContentAreaFilled(false);
        btnConsultar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/Imagens/excluir2.png"))); // NOI18N
        btnExcluir.setBorderPainted(false);
        btnExcluir.setContentAreaFilled(false);
        btnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(247, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVoltar)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConsultar1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnConsultar)
                            .addComponent(btnExcluir)))
                    .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // Voltar para o menu
        Menu menu = new Menu();
        setVisible(false);
        menu.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnConsultar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultar1ActionPerformed
        // TODO add your handling code here:
       
       tblConsulta.setVisible(true);
       DAO dao = new DAO();
       Logica logi = new Logica();         
       
       //Pegando o string do textfield para a realizar a consulta por nome do aluno
       String consulta = txtNome.getText();   
       
       logi.setNome(consulta);      
       logi.setRua(consulta);
       
         try {
             //Chamando o método de pesquisa da classe DAO da conexão com o banco
             dao.pesquisarAlunoNome(logi); 
             
             chave = logi.getIdAlunofk();
             
             if (chave>0)
             
             {
             btnExcluir.setEnabled(true);
             btnConsultar.setEnabled(true);
             }
            
// TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
         }
         /*Comparando o nome e a rua para validar se existe ou não a consulta no banco, pois se não
            existir no banco, o nome e rua serão setados com o mesmo string*/        
         if(logi.getNome().equals(logi.getRua()))
         {      
               btnConsultar.setEnabled(false);
               btnExcluir.setEnabled(false);
               
               if (txtNome.getText().equals("")) 
               {
                 JOptionPane.showMessageDialog(null, "Registros encontrados!", "Alerta", HEIGHT);
               }
               else
               {
                    JOptionPane.showMessageDialog(null, "Não foi encontrado nenhum registro com este nome", "Erro", HEIGHT);
                    txtNome.setText("");
               }
            
               
               //Buscando todos os cadastros do banco novamente caso não encontre nenhum registro no banco 
               ArrayList<Logica>dados = new ArrayList<Logica>();
         try {
             dados = dao.BuscarDadosTodos("select * from aluno, endereco where idAlunofk = idAluno");
         } catch (SQLException ex) {
             Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(Level.SEVERE, null, ex);
         }
       DefaultTableModel modelo = new DefaultTableModel();
         modelo.setColumnIdentifiers(new String[]{"Nome", "Nascimento", "Bairro", "Cidade", "Turma"});
         for(int i=0;i<dados.size();i++) {
         modelo.addRow(
         new Object[]{dados.get(i).getNome(),dados.get(i).getDataNasc(), dados.get(i).getBairro(), dados.get(i).getCidade(),dados.get(i).getTurma()});
         tblConsulta.setModel(modelo);
         }                
        
         // Exibição dos dados na JTable encontre o registro do nome do aluno no banco
         }else{
       
         DefaultTableModel modelo = new DefaultTableModel();
         modelo.setColumnIdentifiers(new String[]{"Nome", "Nascimento", "Bairro", "Cidade", "Turma"});
         
         modelo.addRow(
         new Object[]{logi.getNome(),logi.getDataNasc(), logi.getBairro(), logi.getCidade(),logi.getTurma()});
         tblConsulta.setModel(modelo);      
            }
      
    }//GEN-LAST:event_btnConsultar1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        
        DAO dao = new DAO();
        Logica logi = new Logica();   
        
        nome=txtNome.getText();

        ConsultaAlunoDetalhado consultaAluno = new ConsultaAlunoDetalhado(nome);
        setVisible(false);
        consultaAluno.setVisible(true);
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
       
        btnExcluir.setEnabled(false);
       DAO dao = new DAO();
       Logica logi = new Logica();
       int ide = chave;
       logi.setIdAluno(ide);
       dao.excluirEndereco(ide);
       dao.excluirAluno(ide);

       
          // Buscando todos os dados do banco para exibir no jTable
        ArrayList<Logica>dados = new ArrayList<Logica>();
         try {
             dados = dao.BuscarDadosTodos("select * from aluno, endereco where idAlunofk = idAluno");
         } catch (SQLException ex) {
             Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(Level.SEVERE, null, ex);
         }
       DefaultTableModel modelo = new DefaultTableModel();
         modelo.setColumnIdentifiers(new String[]{"Nome", "Nascimento", "Bairro", "Cidade", "Turma"});
         for(int i=0;i<dados.size();i++) {
         modelo.addRow(
         new Object[]{dados.get(i).getNome(),dados.get(i).getDataNasc(), dados.get(i).getBairro(), dados.get(i).getCidade(),dados.get(i).getTurma()});
         tblConsulta.setModel(modelo);
         }             
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void Teste(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Teste
        // TODO add your handling code here:
     Logica logi = new Logica();
     DAO dao = new DAO();
     
        int k = tblConsulta.getSelectedRow();
    String nomeCampoTabela = (String) tblConsulta.getValueAt(k, 0);
    
       
       
         try {
             
             String consulta = nomeCampoTabela ;   
       
                logi.setNome(consulta);      
                logi.setRua(consulta);
             //Chamando o método de pesquisa da classe DAO da conexão com o banco
             dao.pesquisarAlunoNome(logi); 
             
             chave = logi.getIdAlunofk();
                       
             if (chave>0)
             
             {
             btnExcluir.setEnabled(true);
             btnConsultar.setEnabled(true);
             }
            
// TODO add your handling code here:
         } catch (SQLException ex) {
             Logger.getLogger(CadastroAluno.class.getName()).log(Level.SEVERE, null, ex);
         }
    
   
    txtNome.setText(nomeCampoTabela);
    btnConsultar.setEnabled(true);
    btnExcluir.setEnabled(true);
    
    }//GEN-LAST:event_Teste

    private void tblConsultaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMousePressed
        // TODO add your handling code here:
        tblConsulta.editingCanceled(null);
    }//GEN-LAST:event_tblConsultaMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaAlunoResumo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaAlunoResumo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnConsultar1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblConsulta;
    public javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
