/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.30
 * Generated at: 2020-04-27 20:14:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cadastrar_005fpacientes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1588007218000L));
    _jspx_dependants.put("jar:file:/F:/workspace_final/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Hospital/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098721890000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fresp_005fout_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fresp_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fresp_005fout_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>  \r\n");
      out.write("h1{\r\n");
      out.write("color: #ff3b00;\r\n");
      out.write("font-family: Arial;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-weight: blod;\r\n");
      out.write("}\r\n");
      out.write("h2{\r\n");
      out.write("color: #ff3b00;\r\n");
      out.write("font-family: Arial;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-weight: blod;\r\n");
      out.write("}\t\r\n");
      out.write("table {\r\n");
      out.write("border-width: medium;\r\n");
      out.write("border-style: ridge;\r\n");
      out.write("border-color: #ff3b00;\r\n");
      out.write("border-radius: 30px;\r\n");
      out.write("width: 250px;\r\n");
      out.write("}\r\n");
      out.write("th,tr{\r\n");
      out.write("color: #ff3b00;\r\n");
      out.write("font-family: Arial;\r\n");
      out.write("font-size : 14px;\r\n");
      out.write("font-weight: blod;\r\n");
      out.write("border-width: medium;\r\n");
      out.write("border-style: ridge;\r\n");
      out.write("border-color: #ff3b00;\r\n");
      out.write("border-radius: 25px;\r\n");
      out.write("width: 70px;\r\n");
      out.write("height: 70px;\r\n");
      out.write("}\t\r\n");
      out.write("td {\r\n");
      out.write("color: #ff3b00;\r\n");
      out.write("font-family: Arial;\r\n");
      out.write("font-weight: blod;\r\n");
      out.write("border-radius: 50px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("input {\r\n");
      out.write("font-family: Arial;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-weight: blod;\r\n");
      out.write("border-width: medium;\r\n");
      out.write("border-style: ridge;\r\n");
      out.write("border-color: #ff3b00;\r\n");
      out.write("border-radius: 30px;\r\n");
      out.write("width: 150px; \t\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<form action=\" ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cadastrar_pacientes.pacientes\" method=\"get\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table align=\"center\">\r\n");
      out.write("\t\t<h2>Cadastro de Pacientes</h2>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Nome: </th>\r\n");
      out.write("\t\t\t<td> <input type=\"text\" name=\"nome\" > </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<th>Convenio: </th>\r\n");
      out.write("\t\t\t<td> <input type=\"text\" name=\"convenio\"> </td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" name=\"Enviar\" value=\"Enviar\">\r\n");
      out.write("\t\t\t\t<h3><a href=\"index.jsp\"><h3>Voltar</h3>\r\n");
      out.write("\t\t\t\t</td>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<center>");
      if (_jspx_meth_resp_005fout_005f0(_jspx_page_context))
        return;
      out.write("</center>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_resp_005fout_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  resp:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_resp_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fresp_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_resp_005fout_005f0_reused = false;
    try {
      _jspx_th_resp_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_resp_005fout_005f0.setParent(null);
      // /cadastrar_pacientes.jsp(81,10) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_resp_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menssagem}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_resp_005fout_005f0 = _jspx_th_resp_005fout_005f0.doStartTag();
      if (_jspx_th_resp_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fresp_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_resp_005fout_005f0);
      _jspx_th_resp_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_resp_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_resp_005fout_005f0_reused);
    }
    return false;
  }
}
